### ISSUE TITLE
How to disable Zeebe for tests

### ISSUE THREAD

**Issue by sburkard** [quarkiverse/quarkus-zeebe#169]
Hi 

I have built a Quarkus App that uses the Zeebe extension. 

Now, whenever I run a test class annotated with `@QuarkusTest` the test starts the app and therefore the zeebe client and tries to build and start the workers of the app. This is quite annoying for tests that have no relationship to Zeebe. 

I tried to mock Zeebe away in these tests (`@InjectMock Zeebeclient client`), but I did not find a way to get there. I was also looking for a global property to disable the zeebe client altogether, so I could use it in a `QuarkusTestProfile`, but did not find one. 

How can I disable Zeebe for such tests? 

Thanks and regards
Stephan

**Comment by andrejpetras** [comment]
Fix by: https://github.com/quarkiverse/quarkus-zeebe/pull/280
```
quarkus.zeebe.active=true|false
```
