### ISSUE TITLE
@Variable doesn't work on Kotlin functions, i.e. static methods in Java

### ISSUE THREAD

**Issue by falko** [quarkiverse/quarkus-zeebe#187]

**Comment by andrejpetras** [comment]
@falko currently I have not implemented any support for Kotlin. It would great to have the support for Kotlin. PR's are welcome
The extension `quarkus-scheduler` could serve as an example.

**Comment by falko** [comment]
Well, this issue is not really Kotlin-specific: The code that handles static methods does not support annotations.

**Comment by andrejpetras** [comment]
@falko Do you have an example (or method) that I can use to reproduce this issue?

**Comment by andrejpetras** [comment]
PR: #277
