### ISSUE TITLE
Fail gracefully if the `bpmn`folder doesn't exist

### ISSUE THREAD

**Issue by falko** [quarkiverse/quarkus-zeebe#189]

**Comment by andrejpetras** [comment]
@falko https://docs.quarkiverse.io/quarkus-zeebe/dev/index.html#quarkus-zeebe_quarkus.zeebe.resources.enabled

**Comment by falko** [comment]
I used that as a workaround but it would be nice to not crash even if the feature is enabled.

**Comment by andrejpetras** [comment]
#217
