### ISSUE TITLE
Ignore non-BPMN & non-DMN files in the `bpmn` folder

### ISSUE THREAD

**Issue by falko** [quarkiverse/quarkus-zeebe#190]

**Comment by falko** [comment]
I had a another file in the folder and it crashed the app. But maybe you're right and one shouldn't have other stuff in there.

**Comment by andrejpetras** [comment]
Currently all files in the bpm directory are used as resources for the Zeebe deployment. If you have a use case that makes it useful to have other files in that directory, we can introduce a filter parameter to filter those files (bpmn,dmn, forms, ...). I'm open to any improvement

**Comment by andrejpetras** [comment]
Please reopen this issue if we need to filter the deployment directory to ignore non-deployable resources.
