### ISSUE TITLE
Are there any plans to add assign a user task functionality?

### ISSUE THREAD

**Issue by KricYi** [quarkiverse/quarkus-zeebe#265]
Hi
  zeebe api has added the function of assign a user task. Do you have any plans to add this function?
  
https://docs.camunda.io/docs/apis-tools/zeebe-api-rest/specifications/assign-a-user-task/

**Comment by andrejpetras** [comment]
Hi @KricYi, In the next release, the Zeebe client will have a User Tasks API

**Comment by KricYi** [comment]
That's great! Thank you very much.
