### ISSUE TITLE
Why profile is prod in test

### ISSUE THREAD

**Issue by pipinet** [quarkiverse/quarkus-zeebe#76]
- when i use ZeebeTestResource, profile is prod
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/6096680/177825881-f0ca20e3-899e-47ce-9f49-8488c3b263a2.png">
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/6096680/177825779-49e0192b-a4ad-4986-ab1b-54d853b2d1be.png">

- when i disable ZeebeTestResource, profile is test
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/6096680/177826273-7612a78e-813a-467b-9f8b-7bd4212dc9d5.png">

**Comment by andrejpetras** [comment]
@pipinet the profile of the configuration is `test` in the tests. In the `QuarkusTestResourceLifecycleManager` is it `prod`
I created a simple project where you can check the profiles. Result is
```
##########################
@QuarkusTestResourceLifecycleManager config profiles: [prod]
##########################
2022-07-07 21:17:28,901 INFO  [io.quarkus] (main) rest-json-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.10.2.Final) started in 2.280s. Listening on: http://localhost:8081
2022-07-07 21:17:28,902 INFO  [io.quarkus] (main) Profile test activated. 
2022-07-07 21:17:28,902 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
##########################
Test config profiles:[test]
##########################
```

More info: https://quarkus.io/guides/getting-started-testing#quarkus-test-resource
`By simply annotating any test in the test suite with @QuarkusTestResource, Quarkus will run the corresponding QuarkusTestResourceLifecycleManager before any tests are run.`

I believe this is not an extension issue.
