### ISSUE TITLE
Be a guest on Quarkus Insights podcast?

### ISSUE THREAD

**Issue by insectengine** [quarkiverse/quarkus-zeebe#87]
Hello Andrej,

I help Max Andersen schedule the Quarkus Insights Podcast. Max and I were discussing showcasing extensions on upcoming episodes. 

https://quarkus.io/insights/

I wanted to reach out to you to see if you’re interested in joining us to discuss the Quarkus Unleash, Quarkus Zeebe, and Quarkus MockServer extensions. We are looking to book some time in September or beyond.

Does this sound interesting to you?

Regards,
James
jcobb@redhat.com

**Comment by andrejpetras** [comment]
Hi @insectengine, I am back online. Yes that is interesting. Could we do it some time in October or beyond?

**Comment by insectengine** [comment]
Hi @andrejpetras,
Excellent! We've booked Quarkus Insights episodes through the end of the year but it would be great to have you scheduled for January.

Can you email me at jcobb@redhat.com so we can finalize details?

**Comment by insectengine** [comment]
https://youtube.com/live/LA50HS3jNoE
